const healthResponses = {

 
  // Sintomas respiratórios
  "sore throat": "Gargle with warm salt water and drink fluids. Lozenges can help. If it worsens or lasts more than a few days, consult a doctor.",
  "runny nose": "Stay hydrated and consider using saline nasal spray. If symptoms persist, consult a doctor.",
  "shortness of breath": "If mild, rest and practice deep breathing. If sudden, severe, or persistent, seek emergency medical care.",
  "chest pain": "Chest pain can be serious. If sharp, heavy, or radiating, call emergency services immediately.",

  // Sintomas neurológicos
  "dizziness": "Sit or lie down immediately. Drink water. If recurrent or accompanied by fainting, consult a doctor.",
  "fainting": "Lay the person flat and elevate their legs. Seek medical evaluation after fainting.",
  "seizure": "Ensure safety by moving objects away. Do not restrain the person. Seek emergency medical help.",

  // Sintomas psicológicos
  "anxiety": "Practice deep breathing, meditation, or light exercise. If persistent, consult a mental health professional.",
  "depression": "Talk to someone you trust. Seek professional support. If experiencing suicidal thoughts, seek help immediately.",

  // Sintomas dermatológicos
  "rash": "Keep the area clean and avoid scratching. If spreading, painful, or associated with fever, seek medical care.",
  "itching": "Apply cool compresses or use antihistamine creams. If persistent, consult a dermatologist.",
  "burn": "Cool the burn under running water. Do not apply ice. For severe burns, seek emergency care.",

  // Outros
  "stomach ache": "Rest, drink water, and eat bland foods. If severe or persistent, seek medical advice.",
  "diarrhea": "Drink fluids with electrolytes to prevent dehydration. If it lasts more than 2 days or has blood, consult a doctor.",
  "constipation": "Increase fiber intake, drink water, and exercise. If persistent, consult a healthcare professional.",
  "fatigue": "Rest, maintain hydration, and eat balanced meals. If persistent, consult a doctor.",
  "insomnia": "Keep a regular sleep schedule, avoid caffeine before bedtime, and create a calming environment.",
  "vomiting": "Rest and sip small amounts of fluids. If severe, frequent, or with blood, seek medical care.",
  "ear pain": "Keep the ear dry and avoid inserting objects. If persistent or severe, consult a doctor.",
  "eye pain": "Rest your eyes, avoid screens. If accompanied by vision loss, seek urgent care."
 
  // Sintomas neurológicos
  "dizziness": "Sit or lie down immediately. Drink water. If recurrent or accompanied by fainting, consult a doctor.",
  "fainting": "Lay the person flat and elevate their legs. Seek medical evaluation after fainting.",
  "seizure": "Ensure safety by moving objects away. Do not restrain the person. Seek emergency medical help.",

  // Sintomas psicológicos
  "anxiety": "Practice deep breathing, meditation, or light exercise. If persistent, consult a mental health professional.",
  "depression": "Talk to someone you trust. Seek professional support. If experiencing suicidal thoughts, seek help immediately.",

  // Sintomas dermatológicos
  "rash": "Keep the area clean and avoid scratching. If spreading, painful, or associated with fever, seek medical care.",
  "itching": "Apply cool compresses or use antihistamine creams. If persistent, consult a dermatologist.",
  "burn": "Cool the burn under running water. Do not apply ice. For severe burns, seek emergency care.",

  // Outros
  "stomach ache": "Rest, drink water, and eat bland foods. If severe or persistent, seek medical advice.",
  "diarrhea": "Drink fluids with electrolytes to prevent dehydration. If it lasts more than 2 days or has blood, consult a doctor.",
  "constipation": "Increase fiber intake, drink water, and exercise. If persistent, consult a healthcare professional.",
  "fatigue": "Rest, maintain hydration, and eat balanced meals. If persistent, consult a doctor.",
  "insomnia": "Keep a regular sleep schedule, avoid caffeine before bedtime, and create a calming environment.",
  "vomiting": "Rest and sip small amounts of fluids. If severe, frequent, or with blood, seek medical care.",
  "ear pain": "Keep the ear dry and avoid inserting objects. If persistent or severe, consult a doctor.",
  "eye pain": "Rest your eyes, avoid screens. If accompanied by vision loss, seek urgent care."
 "cough": "Cough can be a symptom of various conditions. Stay hydrated and rest. Seek medical care if it persists.",
  "sore throat": "Gargle with warm salt water and drink fluids. Lozenges may help. See a doctor if it worsens.",
  "runny nose": "Stay hydrated and consider using saline spray. Consult a doctor if persistent.",
  "shortness of breath": "Rest and practice deep breathing. If severe or sudden, seek emergency care.",
  "chest pain": "Can be serious. Call emergency services immediately if sharp, heavy, or radiating.",
  "dizziness": "Sit or lie down immediately. Drink water. Seek medical care if recurrent.",
  "fainting": "Lay flat and elevate legs. Seek medical evaluation.",
  "seizure": "Ensure safety, do not restrain. Seek emergency help.",
  "headache": "Rest, drink water, consider mild pain relievers. Consult doctor if frequent.",
  "confusion": "Monitor and seek medical advice immediately.",
  "anxiety": "Practice deep breathing, meditation, or light exercise. Seek mental health support if persistent.",
  "depression": "Talk to someone trusted. Seek professional support. If suicidal thoughts, seek help immediately.",
  "stress": "Relaxation techniques and proper rest may help. Consult a professional if severe.",
  "insomnia": "Keep a sleep schedule, avoid caffeine, create a calm environment.",
  "mood swings": "Monitor symptoms and consider professional support.",
  "rash": "Keep clean, avoid scratching. Seek medical care if spreading or painful.",
  "itching": "Apply cool compresses or antihistamine cream. Consult a dermatologist if persistent.",
  "burn": "Cool under running water. Do not apply ice. Seek emergency care if severe.",
  "blisters": "Keep clean, avoid popping. Consult a doctor if infected.",
  "eczema": "Moisturize and avoid irritants. Seek dermatology care if persistent.",
  "stomach ache": "Rest, drink fluids, eat bland foods. Seek care if severe or persistent.",
  "nausea": "Sip fluids and rest. Consult doctor if persistent.",
  "vomiting": "Small sips of fluids. Seek care if severe or bloody.",
  "diarrhea": "Drink fluids with electrolytes. Consult doctor if persists or blood present.",
  "constipation": "Increase fiber, drink water, exercise. Seek care if persistent.",
  "muscle pain": "Rest, gentle stretching, pain relievers as needed.",
  "joint pain": "Rest, ice/heat, consult doctor if persistent.",
  "weakness": "Rest and hydrate. Seek evaluation if unexplained.",
  "stiffness": "Stretch and exercise. Consult a professional if severe.",
  "swelling": "Elevate affected area, monitor. Seek care if painful or persistent.",
  "palpitations": "Rest and monitor. Seek urgent care if associated with chest pain.",
  "high blood pressure": "Monitor, lifestyle changes, consult doctor if high readings.",
  "eye pain": "Rest eyes, avoid screens. Seek urgent care if vision changes.",
  "blurred vision": "Check glasses prescription, rest eyes. Consult ophthalmologist if persistent.",
  "red eye": "Avoid rubbing, consult doctor if painful or with discharge.",
  "photophobia": "Rest eyes in dark environment. Seek medical advice if severe.",
  "tearing": "Lubricating drops may help. See doctor if persistent.",
  "ear pain": "Keep ear dry, avoid inserting objects. Consult doctor if persistent.",
  "hearing loss": "Seek audiologist or ENT evaluation.",
  "congestion": "Saline spray, rest. Consult doctor if severe.",
  "hoarseness": "Rest voice, hydrate. See ENT if persists.",
  "cough": "Stay hydrated, rest, and monitor symptoms. Seek medical care if persistent or severe.",
  "sore throat": "Gargle with warm salt water, drink fluids, use lozenges. See a doctor if persistent.",
  "runny nose": "Use saline spray, stay hydrated, rest. Consult doctor if persists.",
  "shortness of breath": "Rest and practice deep breathing. Seek emergency care if severe or sudden.",
  "chest pain": "Can be serious. Call emergency services immediately if sharp or radiating.",
  "dizziness": "Sit or lie down. Drink water. Consult a doctor if recurrent.",
  "fainting": "Lay flat and elevate legs. Seek evaluation after fainting.",
  "seizure": "Ensure safety, do not restrain. Seek emergency help.",
  "headache": "Rest, hydrate, use mild pain relievers. Consult doctor if frequent or severe.",
  "confusion": "Monitor and seek medical attention immediately.",
  "anxiety": "Practice deep breathing, meditation, light exercise. Seek mental health support if persistent.",
  "depression": "Talk to someone trusted. Seek professional support. If suicidal thoughts, seek help immediately.",
  "stress": "Relaxation techniques, proper rest, consult professional if severe.",
  "insomnia": "Maintain sleep schedule, avoid caffeine, create a calm environment.",
  "mood swings": "Monitor symptoms and seek professional support if persistent.",
  "rash": "Keep clean, avoid scratching. Seek medical care if spreading or painful.",
  "itching": "Apply cool compresses or antihistamine cream. Consult dermatologist if persistent.",
  "burn": "Cool under running water. Do not apply ice. Seek emergency care if severe.",
  "blisters": "Keep clean, avoid popping. Consult doctor if infected.",
  "eczema": "Moisturize and avoid irritants. Seek dermatology care if persistent.",
  "stomach ache": "Rest, hydrate, eat bland foods. Seek care if severe or persistent.",
  "nausea": "Sip fluids and rest. Consult doctor if persistent or severe.",
  "vomiting": "Small sips of fluids. Seek care if severe, frequent, or bloody.",
  "diarrhea": "Drink fluids with electrolytes. Seek care if persists or blood present.",
  "constipation": "Increase fiber, hydrate, exercise. Seek care if persistent.",
  "muscle pain": "Rest, gentle stretching, pain relievers as needed.",
  "joint pain": "Rest, ice/heat, consult doctor if persistent.",
  "weakness": "Rest and hydrate. Seek evaluation if unexplained.",
  "stiffness": "Stretch and exercise. Consult professional if severe.",
  "swelling": "Elevate area, monitor. Seek care if painful or persistent.",
  "palpitations": "Rest and monitor. Seek urgent care if chest pain accompanies.",
  "high blood pressure": "Monitor, lifestyle changes, consult doctor if high readings.",
  "eye pain": "Rest eyes, avoid screens. Seek urgent care if vision changes.",
  "blurred vision": "Rest eyes, check prescription, consult ophthalmologist if persists.",
  "red eye": "Avoid rubbing, consult doctor if painful or with discharge.",
  "photophobia": "Rest eyes in dark environment. Seek medical advice if severe.",
  "tearing": "Lubricating drops may help. See doctor if persistent.",
  "ear pain": "Keep ear dry, avoid objects. Consult doctor if persistent.",
  "hearing loss": "Seek audiologist or ENT evaluation.",
  "congestion": "Saline spray, rest. Consult doctor if severe.",
  "hoarseness": "Rest voice, hydrate. See ENT if persists.",
  "painful urination": "Hydrate, avoid irritants. Seek urology evaluation if persistent.",
  "frequent urination": "Monitor fluid intake. Consult doctor if persistent or painful.",
  "blood in urine": "Seek medical attention promptly.",
  "urinary retention": "Do not strain. Seek urgent urology care.",
  "flank pain": "Rest and hydrate. Seek medical attention if severe.",
  "pelvic pain": "Monitor symptoms, consult gynecologist or urologist if persistent.",
  "irregular menstruation": "Track cycles, consult gynecologist if abnormal.",
  "vaginal discharge": "Maintain hygiene, consult gynecologist if unusual.",
  "erectile dysfunction": "Consult healthcare provider for evaluation.",
  "infertility": "Seek specialist evaluation after prolonged attempts.",
  "fever": "Rest, hydrate, monitor temperature. Seek medical care if high or persistent.",
  "fatigue": "Rest, maintain hydration, balanced diet. Consult doctor if persistent.",
  "malaise": "Monitor symptoms. Seek care if persistent or worsening.",
  "weight loss": "Track diet and weight. Consult doctor if unintentional or rapid."
 "cough": "Stay hydrated, rest, and monitor symptoms. Seek medical care if persistent or severe.",
  "sore throat": "Gargle with warm salt water, drink fluids, use lozenges. See a doctor if persistent.",
  "runny nose": "Use saline spray, stay hydrated, rest. Consult doctor if persists.",
  "shortness of breath": "Rest and practice deep breathing. Seek emergency care if severe or sudden.",
  "chest pain": "Can be serious. Call emergency services immediately if sharp or radiating.",
  "dizziness": "Sit or lie down. Drink water. Consult a doctor if recurrent.",
  "fainting": "Lay flat and elevate legs. Seek evaluation after fainting.",
  "seizure": "Ensure safety, do not restrain. Seek emergency help.",
  "headache": "Rest, hydrate, use mild pain relievers. Consult doctor if frequent or severe.",
  "confusion": "Monitor and seek medical attention immediately.",
  "anxiety": "Practice deep breathing, meditation, light exercise. Seek mental health support if persistent.",
  "depression": "Talk to someone trusted. Seek professional support. If suicidal thoughts, seek help immediately.",
  "stress": "Relaxation techniques, proper rest, consult professional if severe.",
  "insomnia": "Maintain sleep schedule, avoid caffeine, create a calm environment.",
  "mood swings": "Monitor symptoms and seek professional support if persistent.",
  "rash": "Keep clean, avoid scratching. Seek medical care if spreading or painful.",
  "itching": "Apply cool compresses or antihistamine cream. Consult dermatologist if persistent.",
  "burn": "Cool under running water. Do not apply ice. Seek emergency care if severe.",
  "blisters": "Keep clean, avoid popping. Consult doctor if infected.",
  "eczema": "Moisturize and avoid irritants. Seek dermatology care if persistent.",
  "stomach ache": "Rest, hydrate, eat bland foods. Seek care if severe or persistent.",
  "nausea": "Sip fluids and rest. Consult doctor if persistent or severe.",
  "vomiting": "Small sips of fluids. Seek care if severe, frequent, or bloody.",
  "diarrhea": "Drink fluids with electrolytes. Seek care if persists or blood present.",
  "constipation": "Increase fiber, hydrate, exercise. Seek care if persistent.",
  "muscle pain": "Rest, gentle stretching, pain relievers as needed.",
  "joint pain": "Rest, ice/heat, consult doctor if persistent.",
  "weakness": "Rest and hydrate. Seek evaluation if unexplained.",
  "stiffness": "Stretch and exercise. Consult professional if severe.",
  "swelling": "Elevate area, monitor. Seek care if painful or persistent.",
  "palpitations": "Rest and monitor. Seek urgent care if chest pain accompanies.",
  "high blood pressure": "Monitor, lifestyle changes, consult doctor if high readings.",
  "eye pain": "Rest eyes, avoid screens. Seek urgent care if vision changes.",
  "blurred vision": "Rest eyes, check prescription, consult ophthalmologist if persists.",
  "red eye": "Avoid rubbing, consult doctor if painful or with discharge.",
  "photophobia": "Rest eyes in dark environment. Seek medical advice if severe.",
  "tearing": "Lubricating drops may help. See doctor if persistent.",
  "ear pain": "Keep ear dry, avoid objects. Consult doctor if persistent.",
  "hearing loss": "Seek audiologist or ENT evaluation.",
  "congestion": "Saline spray, rest. Consult doctor if severe.",
  "hoarseness": "Rest voice, hydrate. See ENT if persists.",
  "painful urination": "Hydrate, avoid irritants. Seek urology evaluation if persistent.",
  "frequent urination": "Monitor fluid intake. Consult doctor if persistent or painful.",
  "blood in urine": "Seek medical attention promptly.",
  "urinary retention": "Do not strain. Seek urgent urology care.",
  "flank pain": "Rest and hydrate. Seek medical attention if severe.",
  "pelvic pain": "Monitor symptoms, consult gynecologist or urologist if persistent.",
  "irregular menstruation": "Track cycles, consult gynecologist if abnormal.",
  "vaginal discharge": "Maintain hygiene, consult gynecologist if unusual.",
  "erectile dysfunction": "Consult healthcare provider for evaluation.",
  "infertility": "Seek specialist evaluation after prolonged attempts.",
  "fever": "Rest, hydrate, monitor temperature. Seek medical care if high or persistent.",
  "fatigue": "Rest, maintain hydration, balanced diet. Consult doctor if persistent.",
  "malaise": "Monitor symptoms. Seek care if persistent or worsening.",
  "weight loss": "Track diet and weight. Consult doctor if unintentional or rapid."
 "irregular menstruation": "Track cycles, consult gynecologist if abnormal.",
  "vaginal discharge": "Maintain hygiene, consult gynecologist if unusual.",
  "menstrual cramps": "Use heat therapy, rest, and consider OTC pain relievers.",
const medicalResponses = {
  // Saúde feminina
  "irregular menstruation": "Track cycles, consult gynecologist if abnormal.",
  "vaginal discharge": "Maintain hygiene, consult gynecologist if unusual.",
  "menstrual cramps": "Use heat therapy, rest, consider OTC pain relievers.",
  "premenstrual syndrome (PMS)": "Track symptoms, use lifestyle changes, OTC medication if needed.",
  "polycystic ovary syndrome (PCOS)": "Monitor cycles, consult endocrinologist for hormonal management.",
  
  // Saúde masculina
  "erectile dysfunction": "Consult healthcare provider for evaluation.",
  "infertility": "Seek specialist evaluation after prolonged attempts.",
  "prostate enlargement (BPH)": "Monitor urinary symptoms, consult urologist for management.",
  "prostatitis": "Seek urologist evaluation, follow prescribed antibiotics or therapy.",
  
  // Sintomas gerais
  "fever": "Rest, hydrate, monitor temperature. Seek medical care if high or persistent.",
  "fatigue": "Rest, maintain hydration, balanced diet. Consult doctor if persistent.",
  "malaise": "Monitor symptoms. Seek care if persistent or worsening.",
  "weight loss": "Track diet and weight. Consult doctor if unintentional or rapid.",
  "headache": "Rest, hydrate, consider OTC pain relief. Seek care if severe or sudden.",
  "cough": "Stay hydrated, monitor symptoms. Seek medical attention if persistent or severe.",
  "shortness of breath": "Rest, practice deep breathing. Seek emergency care if sudden or severe.",
  "chest pain": "Seek immediate medical care; can indicate serious condition.",
  "nausea": "Sip fluids, rest, eat bland foods. Seek medical advice if persistent.",
  "vomiting": "Hydrate, small sips of fluids. Seek care if severe, frequent, or with blood.",
  "diarrhea": "Drink fluids with electrolytes. Seek care if lasting >2 days or bloody.",
  "constipation": "Increase fiber, hydrate, exercise. Seek care if persistent.",
  "rash": "Keep clean, avoid scratching. Seek care if spreading, painful, or with fever.",
  "itching": "Cool compresses or antihistamine creams. Consult dermatologist if persistent.",
  "burn": "Cool under running water. Seek emergency care if severe.",
  "dizziness": "Sit/lie down, hydrate. Seek care if recurrent or with fainting.",
  "fainting": "Lay flat, elevate legs. Seek medical evaluation after episode.",
  "seizure": "Ensure safety, do not restrain. Seek emergency care.",
  "anxiety": "Practice relaxation, meditation. Seek mental health professional if persistent.",
  "depression": "Talk to someone trusted. Seek professional support if persistent or suicidal thoughts.",
  "insomnia": "Maintain sleep routine, avoid caffeine, consult doctor if persistent.",
  "joint pain": "Rest, apply cold/heat, monitor swelling. Seek care if persistent or severe.",
  "back pain": "Maintain posture, physical therapy, seek care if severe or radiating.",
  
  // Clínica Médica
  "Hipertensão arterial": "Monitor blood pressure, maintain healthy diet, exercise. Consult doctor if high or persistent.",
  "Diabetes mellitus tipo 2": "Monitor blood glucose, follow diet and exercise plan. Consult endocrinologist regularly.",
  "Dislipidemia": "Maintain healthy diet, exercise, consider lipid-lowering therapy if prescribed.",
  "Síndrome metabólica": "Monitor weight, blood pressure, glucose, and cholesterol. Lifestyle changes recommended.",
  "Insuficiência cardíaca congestiva": "Monitor symptoms, take medications as prescribed, report worsening signs to doctor.",
  "Doença arterial coronariana": "Follow heart-healthy diet, exercise, and medications. Monitor for chest pain.",
  "Acidente vascular cerebral (AVC)": "Seek emergency care immediately if symptoms occur. Follow secondary prevention plan.",
  "Doença pulmonar obstrutiva crônica (DPOC)": "Avoid smoking, use inhalers as prescribed, monitor breathing.",
  "Asma brônquica": "Use inhalers, avoid triggers, monitor symptoms, seek care if severe attack.",
  "Pneumonia adquirida na comunidade": "Rest, hydrate, take prescribed antibiotics. Seek care if symptoms worsen.",
  "Tuberculose pulmonar": "Follow full antibiotic regimen, monitor symptoms, isolate if active.",
  "Bronquite crônica": "Avoid irritants, use inhalers if prescribed, monitor symptoms.",
  "Hipotireoidismo": "Take prescribed thyroid medication, monitor symptoms, follow up regularly.",
  "Hipertireoidismo": "Follow treatment plan, monitor heart rate and symptoms, consult endocrinologist.",
  "Doença de Addison": "Follow steroid replacement therapy, monitor stress dosing, consult endocrinologist.",
  "Síndrome de Cushing": "Follow treatment plan, monitor cortisol levels, consult endocrinologist.",
  "Anemia ferropriva": "Increase iron intake, consider supplementation. Monitor hemoglobin levels.",
  "Anemia megaloblástica": "Supplement with B12 or folate. Monitor blood counts.",

  // Cardiologia
  "Arritmias cardíacas": "Monitor heart rate, report palpitations or dizziness to doctor.",
  "Fibrilação atrial": "Follow anticoagulation plan, monitor heart rate, report symptoms.",
  "Flutter atrial": "Monitor heart rhythm, follow doctor’s recommendations.",
  "Taquicardia ventricular": "Seek immediate medical attention if symptomatic.",
  "Bradicardia sinusal": "Monitor symptoms, consult cardiologist if fatigue or dizziness occurs.",
  "Hipertensão pulmonar": "Monitor symptoms, follow medications, consult pulmonologist or cardiologist.",
  "Infarto do miocárdio": "Seek immediate medical care; follow secondary prevention plan.",
  "Angina estável": "Follow medications, lifestyle changes, monitor symptoms.",
  "Insuficiência cardíaca direita": "Monitor symptoms, follow treatment plan, consult cardiologist.",
  
  // Neurologia
  "Doença de Alzheimer": "Follow care plan, maintain cognitive exercises, consult neurologist regularly.",
  "Doença de Parkinson": "Follow medication plan, maintain physical therapy, monitor symptoms.",
  "Epilepsia": "Take medications as prescribed, avoid seizure triggers, seek care if seizure frequency changes.",
  "Acidente vascular cerebral isquêmico": "Seek emergency care, follow secondary prevention plan.",
  "Acidente vascular cerebral hemorrágico": "Immediate medical attention required, monitor neurological function.",
  "Esclerose múltipla": "Follow disease-modifying therapy, monitor symptoms, consult neurologist.",
  "Cefaleia tensional": "Rest, hydration, OTC pain relief, stress management.",
  "Enxaqueca": "Avoid triggers, use prescribed medications, maintain headache diary.",
  
  // Pneumologia
  "Enfisema pulmonar": "Avoid smoking, follow medications, monitor breathing.",
  "Embolia pulmonar": "Seek emergency care immediately; follow anticoagulation therapy.",
  "Fibrose pulmonar idiopática": "Follow pulmonologist care, monitor oxygenation, avoid irritants.",
  "Apneia do sono": "Use CPAP if prescribed, maintain sleep hygiene, monitor symptoms.",
  
  // Dermatologia
  "Dermatite": "Keep skin clean, use emollients, consult dermatologist if persistent.",
  "Psoríase": "Follow treatment plan, moisturize, avoid triggers.",
  "Eczema": "Avoid irritants, moisturize, use prescribed topical therapy.",
  
  // Endocrinologia
  "Doença de Graves": "Follow treatment plan, monitor thyroid function, report eye symptoms.",
  "Doença de Hashimoto": "Monitor thyroid function, take prescribed medication, follow up regularly.",
  "Nódulo tireoidiano": "Monitor size, imaging and biopsy if recommended by endocrinologist.",
  "Câncer de tireoide": "Follow surgical and oncological treatment plan, monitor follow-up."

};// Exporta para Node.js
if (typeof module !== "undefined") {
  module.exports = healthResponses;
}

// Exporta para browser (window object)
if (typeof window !== "undefined") {
  window.healthResponses = healthResponses;
}
